--현재 테이블의 인원수
SELECT COUNT(*) AS COUNT
FROM TBL_SCORE;
-->한줄
SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;


--전체 출력 번호,이름,국,영,수 총점 평균 석차

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, ROUND((KOR+ENG+MAT) / 3,1) AS AVG,  RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
FROM TBL_SCORE;
-->한줄
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, ROUND((KOR+ENG+MAT) / 3,1) AS AVG,  RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE
;


SELECT SID, NAME, KOR, ENG, MAT
       , (KOR + ENG + MAT) AS TOT
       , (KOR + ENG + MAT) / 3 AS AVG
       , RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
FROM TBL_SCORE
WHERE NAME LIKE '%' || '동현' || '%';


--이름 검색
SELECT SID, NAME, KOR, ENG, MAT, TOT, AVG, RANK
FROM
(SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT) / 3 AS AVG, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE)T
WHERE NAME LIKE '%' || '동현' || '%';

-->한줄로
SELECT SID, NAME, KOR, ENG, MAT, TOT, AVG, RANK FROM (SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT) / 3 AS AVG, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE) WHERE NAME LIKE '%' || '동현' || '%'
;



----번호 검색
SELECT SID, NAME, KOR, ENG, MAT, TOT, AVG, RANK
FROM
(SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT) / 3 AS AVG, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE)T
WHERE SID = 1;

--성적 수정
UPDATE TBL_SCORE
SET NAME = '유동현', KOR = 50, ENG = 50, MAT = 50
WHERE SID = 1;
-->한줄로
UPDATE TBL_SCORE SET NAME = '유동현', KOR = 50, ENG = 50, MAT = 50 WHERE SID = 1
;

COMMIT;

--삭제
SELECT *
FROM TBL_SCORE
WHERE SID = 1;

--한줄로
DELETE FROM TBL_SCORE WHERE SID = 1
;


SELECT *
FROM TBL_SCORE;