SELECT USER
FROM DUAL;

DROP TABLE TBL_MEMBERLIST PURGE;



--○실습 테이블 다시 생성
CREATE TABLE TBL_MEMBERLIST
( MID   NUMBER
, NAME  VARCHAR2(30)
, TELEPHONE VARCHAR2(50)
, CONSTRAINT MEMBERLIST_MID_PK PRIMARY KEY(MID)
);

--Table TBL_MEMBERLIST이(가) 생성되었습니다.


--○ 시퀀스 생성
CREATE SEQUENCE MEMBERLISTSEQ
NOCACHE;
--Sequence MEMBERLISTSEQ이(가) 생성되었습니다.

--○ 샘플 데이터 입력
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE)
VALUES(MEMBERLISTSEQ.NEXTVAL, '박원석', '010-1111-1111');
-->한 줄 구성
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE) VALUES(MEMBERLISTSEQ.NEXTVAL, '박원석', '010-1111-1111')
;

INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE) VALUES(MEMBERLISTSEQ.NEXTVAL, '유동현', '010-3578-3912')
;


--○ 화긴
SELECT *
FROM TBL_MEMBERLIST;

--○ 커밋
COMMIT;
--==>> 커밋 완료.


--○ 리스트 조회 쿼리문 구성
SELECT MID, NAME, TELEPHONE
FROM TBL_MEMBERLIST
ORDER BY MID;
--> 한 줄 구성
SELECT MID, NAME, TELEPHONE FROM TBL_MEMBERLIST ORDER BY MID
;

UPDATE TBL_MEMBERLIST
SET TELEPHONE = '010-5555-5555'
WHERE MID = 4;
--==>>
/*
1   민찬우   010-1111-1111
2   김태민   010-2222-2222
*/


--○ 인원 수 조회 쿼리문 구성
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERLIST;
--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERLIST
;
--==>> 2

