SELECT USER
FROM DUAL;
--==>SCOTT


SELECT 1+2
FROM DUAL;

DROP TABLE REGION;

PURGE RECYCLEBIN;

DROP SEQUENCE REGIONSEQ;

--¡Û½Ç½À Å×ÀÌºí »ý¼º(Áö¿ª)
CREATE TABLE REGION
( REGIONID  NUMBER      --Áö¿ª ¾ÆÀÌµð  -- PK
, REGIONNAME    VARCHAR2(30)  --Áö¿ª ÀÌ¸§
, CONSTRAINT    REGION_ID_PK PRIMARY KEY(REGIONID)
);

--Table REGIONÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û ½ÃÄö½º »ý¼º(Áö¿ª : REGIONSEQ)

CREATE SEQUENCE REGIONSEQ
NOCACHE;
--Sequence REGIONSEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û µ¥ÀÌÅÍ ÀÔ·Â (Áö¿ª µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '¼­¿ï');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'ÀÎÃµ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '´ë±¸');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '±¤ÁÖ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '´ëÀü');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'ºÎ»ê');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '¿ï»ê');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '°æ±â');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '°­¿ø');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'ÃæºÏ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'Ãæ³²');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'ÀüºÏ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'Àü³²');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '°æºÏ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, '°æ³²');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL, 'Á¦ÁÖ');


-- 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù. * 16


SELECT *
FROM REGION;

--¡Ûµ¥ÀÌÅÍ Ä¿¹Ô
COMMIT;

DROP TABLE POSITION;

DROP SEQUENCE POSITIONSEQ;

--¡Û ½Ç½À Å×ÀÌºí »ý¼º
CREATE TABLE POSITION
( POSITIONID    NUMBER      -- Á÷À§ ¾ÆÀÌµð   --PK
, POSITIONNAME VARCHAR2(30) -- Á÷À§ ÀÌ¸§
, MINBASICPAY   NUMBER      --ÇØ´ç Á÷À§ÀÇ ÃÖ¼Ò ±âº»±Þ
, CONSTRAINT POSITION_ID_PK PRIMARY KEY(POSITIONID)
);

--Table POSITIONÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


--¡Û ½ÃÄö½º »ý¼º (Á÷À§ : POSITIONSEQ)
CREATE SEQUENCE POSITIONSEQ
NOCACHE;

--Sequence POSITIONSEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û µ¥ÀÌÅÍ ÀÔ·Â (Á÷À§ µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '»ç¿ø', 1000000);    --¹é¸¸
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '´ë¸®', 2000000);     --ÀÌ¹é¸¸
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '°úÀå', 3000000);
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, 'ºÎÀå', 4000000);
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '»ó¹«', 5000000);     --¿À¹é¸¸
--1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù. * 5


--È®ÀÎ
SELECT *
FROM POSITION;
/*
1	»ç¿ø	1000000
2	´ë¸®	2000000
3	°úÀå	3000000
4	ºÎÀå	4000000
5	»ó¹«	5000000
*/

--¡Û Ä¿¹Ô
COMMIT;

DROP TABLE DEPARTMENT;

DROP SEQUENCE DEPARTMENTSEQ;

--¡Û ½Ç½À Å×ÀÌºí »ý¼º (ºÎ¼­ : DEPARTMENT)
CREATE TABLE DEPARTMENT
( DEPARTMENTID  NUMBER      --ºÎ¼­ ¾ÆÀÌµð --PK
, DEPARTMENTNAME VARCHAR2(30)   --ºÎ¼­ ÀÌ¸§
, CONSTRAINT DEPARTMENT_ID_PK PRIMARY KEY(DEPARTMENTID)
);
--Table DEPARTMENTÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


--¡Û ½ÃÄö½º »ý¼º(ºÎ¼­ : DEPARTMENTSEQ)
CREATE SEQUENCE DEPARTMENTSEQ
NOCACHE;

--Sequence DEPARTMENTSEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û µ¥ÀÌÅÍ ÀÔ·Â (ºÎ¼­ µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL, '°³¹ßºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL, '±âÈ¹ºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL, '¿µ¾÷ºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL, 'ÀÎ»çºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL, '»ç¾÷ºÎ');

--1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù. * 5

SELECT *
FROM DEPARTMENT;

--Ä¿¹Ô
COMMIT;
--==>Ä¿¹Ô ¿Ï·á.

--¡Û½Ç½À Å×ÀÌºí »ý¼º (EMPLOYEE)
--»ç¿ø¹øÈ£, »ç¿ø¸í, ÁÖ¹Î¹øÈ£, »ý³â¿ùÀÏ, ¾çÀ½·Â, ÀüÈ­¹øÈ£, ºÎ¼­, Á÷À§, Áö¿ª, ±âº»±Þ, ¼ö´ç
CREATE TABLE EMPLOYEE
( EMPLOYEEID    NUMBER              --»ç¿ø¹øÈ£      -PK
, NAME          VARCHAR2(30)        --»ç¿ø ÀÌ¸§
, SSN           VARCHAR2(30)        --ÁÖ¹Î ¹øÈ£     --¾ÏÈ£È­ ±â´É Àû¿ë(Å¸ÀÔ CHECK~!!!)
, BIRTHDAY      DATE                --»ý³â¿ùÀÏ
, LUNAR         NUMBER(1) DEFAULT 0 --¾çÀ½·Â           --¾ç·Â 0 , À½·Â 1
, TELEPHONE     VARCHAR2(40)        --ÀüÈ­¹øÈ£
, DEPARTMENTID  NUMBER              --ºÎ¼­ ¾ÆÀÌµð --FK
, POSITIONID    NUMBER              --Á÷À§ ¾ÆÀÌµð --FK
, REGIONID      NUMBER              --Áö¿ª ¾ÆÀÌµð --FK
, BASICPAY      NUMBER              --±âº»±Þ
, EXTRAPAY      NUMBER              --¼ö´ç
, CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(EMPLOYEEID)
, CONSTRAINT EMPLOYEE_DEPARTMENTID_FK FOREIGN KEY(DEPARTMENTID)
                                REFERENCES DEPARTMENT(DEPARTMENTID)
, CONSTRAINT EMPLOYEE_POSITIONID_FK FOREIGN KEY(POSITIONID)
            REFERENCES POSITION(POSITIONID)
, CONSTRAINT EMPLOYEE_REGIONID_FK FOREIGN KEY(REGIONID)
            REFERENCES REGION(REGIONID)
, CONSTRAINT EMPLOYEE_LUNAR_CK CHECK(LUNAR=0 OR LUNAR =1)
);

--Table EMPLOYEEÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


--¡Û ½ÃÄö½º »ý¼º( Á÷¿ø : EMPLOYEESEQ)
 CREATE SEQUENCE EMPLOYEESEQ
 NOCACHE;
--Sequence EMPLOYEESEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--µ¥ÀÌÅÍ ÀÔ·Â Á÷¿ø µ¥ÀÌÅÍ ÀÔ·Â

INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE
                       , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES(EMPLOYEESEQ.NEXTVAL, '¾ö¼Ò¿¬', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567')
        , TO_DATE('1994-11-24','YYYY-MM-DD'), 0, '010-7193-4562', 1,1,1, 1500000, 1500000);


INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY) VALUES(EMPLOYEESEQ.NEXTVAL, '¾ö¼Ò¿¬', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567'), TO_DATE('1994-11-24','YYYY-MM-DD'), 0, '010-7193-4562', 1,1,1, 1500000, 1500000)
;

DELETE FROM EMPLOYEE WHERE EMPLOYEEID = ?
;

UPDATE EMPLOYEE 
SET NAME = '¾ö¼Ò¿¬', SSN1 = CRYPTPACK.ENCRYPT('9011242234567', '9011242234567')
WHERE EMPLOYEEID = 1;

DESC EMPLOYEE;


SELECT *
FROM EMPLOYEE;

--1	¾ö¼Ò¿¬	?`??$?	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000

COMMIT;

--¡Û Á÷¿ø Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, '¾ç·Â', 1, 'À½·Â') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
     , E.POSITIONID AS POSITONID
     , (SELECT POSITIONNAME
        FROM POSITION
        WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
     , E.REGIONID AS REGIONID
     , (SELECT REGIONNAME
        FROM REGION
        WHERE REGIONID = E.REGIONID) AS REGIONNAME
     , E.BASICPAY AS BASICPAY
     , E.EXTRAPAY AS EXTRAPAY
     , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
FROM EMPLOYEE E;



--¡Û ºä »ý¼º (EMPLOYEEVIEW)

CREATE OR REPLACE VIEW EMPLOYEEVIEW
AS
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, '¾ç·Â', 1, 'À½·Â') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
     , E.POSITIONID AS POSITONID
     , (SELECT POSITIONNAME
        FROM POSITION
        WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
     , E.REGIONID AS REGIONID
     , (SELECT REGIONNAME
        FROM REGION
        WHERE REGIONID = E.REGIONID) AS REGIONNAME
     , E.BASICPAY AS BASICPAY
     , E.EXTRAPAY AS EXTRAPAY
     , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
FROM EMPLOYEE E;

--View EMPLOYEEVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.




--¡Û Áö¿ª Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
--  Æ¯Á¤ Áö¿ª µ¥ÀÌÅÍ »èÁ¦ °¡´É ¿©ºÎ È®ÀÎ

SELECT R.REGIONID AS REGIONID
    , R.REGIONNAME AS REGIONNAME
    , ( SELECT COUNT(*)
    FROM EMPLOYEE
    WHERE REGIONID = R.REGIONID) AS DELCHECK
FROM REGION R;

SELECT R.REGIONID AS REGIONID, R.REGIONNAME AS REGIONNAME, ( SELECT COUNT(*) FROM EMPLOYEE WHERE REGIONID = R.REGIONID) AS DELCHECK FROM REGION R
;

/*
1	¼­¿ï	1
2	ÀÎÃµ	0
3	´ë±¸	0
4	±¤ÁÖ	0
5	´ëÀü	0
*/
-- ¼­¿ï ÀÇ Áö¿ª Á¤º¸´Â »èÁ¦°¡ ºÒ°¡´ÉÇÑ µ¥ÀÌÅÍÀÌ¸ç
-- ±× ¿Ü ³ª¸ÓÁö Áö¿ª Á¤º¸´Â »èÁ¦°¡ °¡´ÉÇÑ µ¥ÀÌÅÍÀÓÀ» ÆÇº°ÇÒ ¼ö ÀÖµµ·Ï ±¸¼ºÇÑ Äõ¸®¹®,

--¡Ø ºä »ý¼º (Áö¿ª Á¤º¸ : REGIONVIEW)
CREATE OR REPLACE VIEW REGIONVIEW
AS
SELECT R.REGIONID AS REGIONID
    , R.REGIONNAME AS REGIONNAME
    , ( SELECT COUNT(*)
    FROM EMPLOYEE
    WHERE REGIONID = R.REGIONID) AS DELCHECK
FROM REGION R;
--View REGIONVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


--¡Û Á÷À§ Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
--  Æ¯Á¤ Á÷À§ µ¥ÀÌÅÍ »èÁ¦ °¡´É ¿©ºÎ È®ÀÎ

SELECT P.POSITIONID AS POSITIONID
        , P.POSITIONNAME AS POSITIONNAME
        , P.MINBASICPAY AS MINBASICPAY
        , (SELECT COUNT(*)
          FROM EMPLOYEE
          WHERE POSITIONID = P.POSITIONID) AS DELCHECK
FROM POSITION P;


--¡Ø ºä »ý¼º (Á÷À§ Á¤º¸ : POSITIONVIEW)

CREATE OR REPLACE VIEW POSITIONVIEW
AS
SELECT P.POSITIONID AS POSITIONID
        , P.POSITIONNAME AS POSITIONNAME
        , P.MINBASICPAY AS MINBASICPAY
        , (SELECT COUNT(*)
          FROM EMPLOYEE
          WHERE POSITIONID = P.POSITIONID) AS DELCHECK
FROM POSITION P;

--View REGIONVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

SELECT * FROM POSITIONVIEW;

--¡Û ºÎ¼­ Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
--  Æ¯Á¤ ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦ °¡´É ¿©ºÎ È®ÀÎ
SELECT D.DEPARTMENTID AS DEPARTMENTID
    , D.DEPARTMENTNAME AS DEPARTMENTNAME
    ,(SELECT COUNT(*)
    FROM EMPLOYEE
    WHERE DEPARTMENTID = D.DEPARTMENTID) AS DELCHECK
FROM DEPARTMENT D;

--¡Ø ºä »ý¼º (ºÎ¼­ Á¤º¸ : DEPARTMENTVIEW)
CREATE OR REPLACE VIEW DEPARTMENTVIEW
AS
SELECT D.DEPARTMENTID AS DEPARTMENTID
    , D.DEPARTMENTNAME AS DEPARTMENTNAME
    ,(SELECT COUNT(*)
    FROM EMPLOYEE
    WHERE DEPARTMENTID = D.DEPARTMENTID) AS DELCHECK
FROM DEPARTMENT D;
--View DEPARTMENTVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

SELECT * 
FROM DEPARTMENTVIEW;
/*
1	°³¹ßºÎ	1
2	±âÈ¹ºÎ	0
3	¿µ¾÷ºÎ	0
*/


--ºÎ¼­ ÀüÃ¼ µ¥ÀÌÅÍ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK
FROM DEPARTMENTVIEW
ORDER BY DEPARTMENTID;

--ÇÑÁÙ ±¸¼º
SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK FROM DEPARTMENTVIEW ORDER BY DEPARTMENTID
;


--ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º( ºÎ¼­ ¹øÈ£·Î ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦)
DELETE
FROM DEPARTMENT
WHERE DEPARTMENTID = 1;

--ÇÑÁÙ ±¸¼º
DELETE FROM DEPARTMENT WHERE DEPARTMENTID = 1
;

--ºÎ¼­ µ¥ÀÌÅÍ ¼öÁ¤ Äõ¸®¹® ±¸¼º
UPDATE DEPARTMENT
SET DEPARTMENTNAME = 'ÃÑ¹«ºÎ'
WHERE DEPARTMENTID = 1;

--ÇÑÁÙ
UPDATE DEPARTMENT SET DEPARTMENTNAME = 'ÃÑ¹«ºÎ' WHERE DEPARTMENTID = 1
;


--Áö¿ª ÀüÃ¼ µ¥ÀÌÅÍ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT REGIONID, REGIONNAME, DELCHECK
FROM REGIONVIEW
ORDER BY REGIONID;

--ÇÑÁÙ
SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW ORDER BY REGIONID
;

/*
1	¼­¿ï	1
2	ÀÎÃµ	0
3	´ë±¸	0
4	±¤ÁÖ	0
5	´ëÀü	0
6	ºÎ»ê	0
7	¿ï»ê	0
8	°æ±â	0
9	°­¿ø	0
10	ÃæºÏ	0
11	Ãæ³²	0
12	ÀüºÏ	0
13	Àü³²	0
14	°æºÏ	0
15	°æ³²	0
16	Á¦ÁÖ	0
*/

--Áö¿ª µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º (Áö¿ª ¹øÈ£·Î Áö¿ª µ¥ÀÌÅÍ »èÁ¦)

DELETE
FROM REGION
WHERE REGIONID = 1;

--ÇÑÁÙ

DELETE FROM REGION WHERE REGIONID = 1
;


--Áö¿ª µ¥ÀÌÅÍ ¼öÁ¤ Äõ¸®¹® ±¸¼º (Áö¿ª ¹øÈ£·Î Áö¿ª ÀÌ¸§ º¯°æ)
UPDATE REGION
SET REGIONNAME = 'Áö¿ª¸í'
WHERE REGIONID = 1;

--ÇÑÁÙ ±¸¼º
UPDATE REGION SET REGIONNAME = 'Áö¿ª¸í' WHERE REGIONID = 1
;


--Á÷À§ ÀüÃ¼ µ¥ÀÌÅÍ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK
FROM POSITIONVIEW
ORDER BY POSITIONID;


--ÇÑÁÙ
SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW ORDER BY POSITIONID

SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW ORDER BY POSITIONID

SELECT MINBASICPAY FROM POSITIONVIEW WHERE POSITIONID = 1

;
/*
1	»ç¿ø	1000000	1
2	´ë¸®	2000000	0
3	°úÀå	3000000	0
4	ºÎÀå	4000000	0
5	»ó¹«	5000000	0
*/

--Á÷À§ µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º (Á÷À§¹øÈ£·Î Á÷À§ µ¥ÀÌÅÍ »èÁ¦)
DELETE
FROM POSITION
WHERE POSITIONID=1;

--ÇÑÁÙ

DELETE FROM POSITION WHERE POSITIONID=1
;


--Áö¿ª µ¥ÀÌÅÍ ¼öÁ¤ Äõ¸®¹® ±¸¼º (Áö¿ª¹øÈ£·Î Áö¿ª ÀÌ¸§ º¯°æ)
UPDATE POSITION
SET POSITIONNAME = 'Á÷À§¸í'
    , MINBASICPAY = 3000000
WHERE POSITIONID = 1;

--ÇÑÁÙ
UPDATE POSITION  SET POSITIONNAME = 'Á÷À§¸í' , MINBASICPAY = 3000000 WHERE POSITIONID = 1
;


ROLLBACK;



-------------------------------------------------------------------------------------
--¡á¡á¡á ·Î±×ÀÎ / ·Î±×¾Æ¿ô ±â´É Àû¿ë °úÁ¤ Ãß°¡ ¡á¡á¡á-----

--ÇöÀç ¿ì¸®°¡ ±¸¼ºÇÑ Å×ÀÌºí ±¸Á¶´Â ID¿Í PW ÄÃ·³ Á¤º¸¸¦ ´ã°íÀÖ´Â Å×ÀÌºíÀÌ
-- º°µµ·Î Á¸ÀçÇÏÁö ¾Ê´Â »óÈ²ÀÌ´Ù.
-- ÀÌ¿Í °ü·ÃÇÏ¿© EMPLOYEEID(»ç¿ø¾ÆÀÌµð) ¿Í SSN(ÁÖ¹Î¹øÈ£) µÞÀÚ¸® 7ÀÚ¸®ÀÇ ¼ýÀÚ¸¦
-- È°¿ëÇÏ¿© ±â´ÉÀ» ±¸ÇöÇÒ ¼ö ÀÖµµ·Ï Ã³¸®ÇÑ´Ù.

--¡Ø ±âÁ¸ Å×ÀÌºí ±¸Á¶ º¯°æ
--¨ç
-- EMPLOYEE (Á÷¿ø µ¥ÀÌÅÍ Å×ÀÌºí)ÀÇ SSN(ÁÖ¹Î¹øÈ£) ÄÃ·³À» ºÐ¸®ÇÑ´Ù.
-- SSN ------------------->SSN1, SSN2
-- SSN1 ---------------->ÁÖ¹Î¹øÈ£ ¾Õ 6ÀÚ¸®
-- SSN2 ----------------->ÁÖ¹Î¹øÈ£ µÞ 7ÀÚ¸® -> ¾ÏÈ£È­ Àû¿ë

--¨è
-- EMPLOYEE(Á÷¿ø Å×ÀÌºí)ÀÇ GRADE(µî±Þ) ÄÃ·³À» Ãß°¡ÇÑ´Ù.
-- GRADE ¡æ 0:°ü¸®ÀÚ, 1:ÀÏ¹Ý»ç¿ø


--¡Û ÄÃ·³ ºÐÇÒ SSN ¡æ SSN1, SSN2

-- ÄÃ·³ Ãß°¡
ALTER TABLE EMPLOYEE
ADD(SSN1 CHAR(6), SSN2 VARCHAR2(50));
--==>> Table EMPLOYEEÀÌ(°¡) º¯°æµÇ¾ú½À´Ï´Ù.


SELECT *
FROM EMPLOYEE;
--1	¾ö¼Ò¿¬	?`??$?	1994-11-24	0	010-7193-4562	1	1	1	1500000	150000  NULL  NULL

-- SSN ¡æ ¾ÏÈ£È­('9610041234567', '9610041234567')

-- SSN1 ¡æ SUBSTR(º¹È£È­(´ë»ó, '9610041234567'), 1, 6) ¡æ '961004'
-- SSN2 ¡æ ¾ÏÈ£È­(SUBSTR(º¹È£È­(´ë»ó, '9610041234567'), 7, 7)
--              , SUBSTR(º¹È£È­(´ë»ó, '9610041234567'), 7, 7)) ¡æ '1234567'

UPDATE EMPLOYEE
SET  SSN1 = SUBSTR(CRYPTPACK.DECRYPT(SSN,'9411242234567') ,1,6)
    , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(CRYPTPACK.DECRYPT(SSN,'9411242234567'),7,7),SUBSTR(CRYPTPACK.DECRYPT(SSN,'9411242234567'),7,7))
WHERE EMPLOYEEID = 1;

SELECT *
FROM EMPLOYEE;


COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.


--¨ç-1 ±âÁ¸ ÁÖ¹Î¹øÈ£ ÄÃ·³(SSN) Á¦°Å
ALTER TABLE EMPLOYEE
DROP COLUMN SSN;
--==>> Table EMPLOYEEÀÌ(°¡) º¯°æµÇ¾ú½À´Ï´Ù.

--¨è-1 GRADE ÄÃ·³ Ãß°¡ ¡æ ±âº»°ªÀ» 1(ÀÏ¹Ý»ç¿ø)·Î ±¸¼º
ALTER TABLE EMPLOYEE
ADD GRADE NUMBER(1) DEFAULT 1;
--==>>Table EMPLOYEEÀÌ(°¡) º¯°æµÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;



--¨è-2 ¾ö¼Ò¿¬ »ç¿øÀ» °ü¸®ÀÚ·Î ÀÓ¸í(¼³Á¤)
UPDATE EMPLOYEE
SET GRADE=0
WHERE EMPLOYEEID = 1;
--==>>1Çà ÀÌ ¾÷µ¥ÀÌÆ® µÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;
--1	¾ö¼Ò¿¬	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	0

--¡ÛÄ¿¹Ô
COMMIT;
--Ä¿¹Ô ¿Ï·á.

--Å×ÀÌºíÀÇ ±¸Á¶¸¦ º¯°æÇß±â ¶§¹®¿¡
-- ÀÌ Å×ÀÌºí(EMPLOYEE)¸¦ ±â¹ÝÀ¸·Î »ý¼ºÇÑ ºäÀÇ ³»¿ëÀ» ¼öÁ¤

CREATE OR REPLACE VIEW EMPLOYEEVIEW
AS
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN1 AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, '¾ç·Â', 1, 'À½·Â') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
     , E.POSITIONID AS POSITIONID
     , (SELECT POSITIONNAME
        FROM POSITION
        WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
     , E.REGIONID AS REGIONID
     , (SELECT REGIONNAME
        FROM REGION
        WHERE REGIONID = E.REGIONID) AS REGIONNAME
     , E.BASICPAY AS BASICPAY
     , E.EXTRAPAY AS EXTRAPAY
     , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
     , E.GRADE AS GRADE
FROM EMPLOYEE E;

SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, LUNARNAME, TELEPHONE, DEPARTMENTID, DEPARTMENTNAME, POSITIONID, POSITIONNAME, REGIONID, REGIONNAME, BASICPAY, EXTRAPAY, PAY, GRADE FROM EMPLOYEEVIEW
;

-- 1	¾ö¼Ò¿¬	941124	1994-11-24	0	¾ç·Â	010-7193-4562	1	°³¹ßºÎ	1	»ç¿ø	1	¼­¿ï	1500000	1500000	3000000	0


--¡Ûµ¥ÀÌÅÍ ÀÔ·Â (Á÷¿ø µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN1, SSN2, BIRTHDAY, LUNAR, TELEPHONE
                       , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES(EMPLOYEESEQ.NEXTVAL, 'Á¤¹Ì°æ', '981009',CRYPTPACK.ENCRYPT('2345678', '2345678')
        , TO_DATE('1998-10-09','YYYY-MM-DD'), 0, '010-3098-3091', 1,1,8, 1500000, 1500000);
--==>>1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;
/*
1	¾ö¼Ò¿¬	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	0
2	Á¤¹Ì°æ	1998-10-09	0	010-3098-3091	1	1	8	1500000	1500000	981009	?r??o	1
*/
SELECT *
FROM EMPLOYEEVIEW;
/*
1	¾ö¼Ò¿¬	941124	1994-11-24	0	¾ç·Â	010-7193-4562	1	°³¹ßºÎ	1	»ç¿ø	1	¼­¿ï	1500000	1500000	3000000	0
2	Á¤¹Ì°æ	981009	1998-10-09	0	¾ç·Â	010-3098-3091	1	°³¹ßºÎ	1	»ç¿ø	8	°æ±â	1500000	1500000	3000000	1
*/
COMMIT;


------------------------------------------------------------------------------

--ÀÏ¹Ý»ç¿ø ·Î±×ÀÎ Äõ¸®¹® ±¸¼º(¾ÆÀÌµð, ÆÐ½º¿öµå)
--¾ÆÀÌµð : »ç¿ø¹øÈ£
-- ÆÐ½º¿öµå : ÁÖ¹Î¹øÈ£ µÞÀÚ¸®
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = ¾ÆÀÌµð
   AND SSN2 = ÆÐ½º¿öµå;
      
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 2
   AND SSN2 = CRYPTPACK.ENCRYPT('2345678','2345678');     
--==>Á¤¹Ì°æ
-->·Î±×ÀÎ ¼º°ø~!!!!

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 2
   AND SSN2 = CRYPTPACK.ENCRYPT('1234566','1234566');     
--==>
-->·Î±×ÀÎ ½ÇÆÐ~!!!!


SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
   AND SSN2 = CRYPTPACK.ENCRYPT('2234567','2234567');     
--==>¾ö¼Ò¿¬
-->·Î±×ÀÎ ¼º°ø~!!!!

--ÀÏ¹Ý »ç¿ø ·Î±×ÀÎ Äõ¸®¹® ÇÑ ÁÙ ±¸¼º
SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = 'ID¹®ÀÚ¿­' AND SSN2 = CRYPTPACK.ENCRYPT('PW¹®ÀÚ¿­','PW¹®ÀÚ¿­')
;     
--==>Á¤¹Ì°æ
-->·Î±×ÀÎ ¼º°ø~!!!!


-- °ü¸®ÀÚ ·Î±×ÀÎ Äõ¸®¹® ±¸¼º(¾ÆÀÌµð,ÆÐ½º¿öµå,µî±Þ)
--¾ÆÀÌµð : »ç¿ø¹øÈ£
-- ÆÐ½º¿öµå : ÁÖ¹Î¹øÈ£ µÞÀÚ¸®
-- µî±Þ : GRADE

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID=¾ÆÀÌµð
    AND SSN2 =ÆÐ½º¿öµå
    AND GRADE = 0;
    
    
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID=2
    AND SSN2 =CRYPTPACK.ENCRYPT('2345678','2345678')
    AND GRADE = 0;
    --==>>Á¶È¸°á°ú ¾øÀ½
    --> °ü¸®ÀÚ·Î ·Î±×ÀÎ ½ÇÆÐ

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID=1
    AND SSN2 =CRYPTPACK.ENCRYPT('2234567','2234567')
    AND GRADE = 0;
--==>>¾ö¼Ò¿¬
-->°ü¸®ÀÚ·Î ·Î±×ÀÎ ¼º°ø~!!

--°ü¸®ÀÚ ·Î±×ÀÎ Äõ¸®¹® ÇÑ ÁÙ ±¸¼º
SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID='ID¹®ÀÚ¿­' AND SSN2 =CRYPTPACK.ENCRYPT('PW¹®ÀÚ¿­','PW¹®ÀÚ¿­') AND GRADE = 0
;


DESC EMPLOYEE;


SELECT 
       , NAME, SSN1, CRYPTPACK.DECRYPT(SSN2,'aa'), TO_CHAR(BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
       , LUNAR, TELEPHONE, DEPARTMENTID, POSITIONID, REGIONID
       , BASICPAY, EXTRAPAY
        FROM EMPLOYEE
        WHERE EMPLOYEEID=1;

SELECT CRYPTPACK.DECRYPT(SSN2,'1234567') AS SSN2 FROM EMPLOYEE WHERE EMPLOYEEID = 3
;


SELECT *
FROM POSITION;


--ÀÏ¹Ý Á÷¿øÀÇ ¸®½ºÆ® Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNARNAME, TELEPHONE
       , DEPARTMENTNAME, POSITIONNAME, REGIONNAME
FROM EMPLOYEEVIEW
ORDER BY EMPLOYEEID;

--ÇÑÁÙ ±¸¼º
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNARNAME, TELEPHONE, DEPARTMENTNAME, POSITIONNAME, REGIONNAME FROM EMPLOYEEVIEW ORDER BY EMPLOYEEID
;




select *
from employeeview;

SELECT * FROM REGION
;

UPDATE REGION SET REGIONNAME= ? WHERE REGIONID = ?
;


desc departmentview;

select * from positionview;


SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW ORDER BY POSITIONID
;

select * from position;
