SELECT USER
FROM DUAL;


DROP TABLE TBL_MEMBER;

PURGE RECYCLEBIN;


CREATE TABLE TBL_MEMBER
( SID NUMBER
, NAME VARCHAR2(30)
, TEL VARCHAR2(40)
, CONSTRAINT MEMBER_SID_PK PRIMARY KEY(SID)
);


--시퀀스 제거
DROP SEQUENCE MEMBERSEQ;


CREATE SEQUENCE MEMBERSEQ
NOCACHE;



--샘플 데이터 입력
INSERT INTO TBL_MEMBER(SID,NAME,TEL) VALUES(MEMBERSEQ.NEXTVAL, '조현하', '010-1111-1111');
INSERT INTO TBL_MEMBER(SID,NAME,TEL) VALUES(MEMBERSEQ.NEXTVAL, '임시연', '010-2222-2222');
INSERT INTO TBL_MEMBER(SID,NAME,TEL) VALUES(MEMBERSEQ.NEXTVAL, '최나윤', '010-3333-3333');
INSERT INTO TBL_MEMBER(SID,NAME,TEL) VALUES(MEMBERSEQ.NEXTVAL, '반보영', '010-4444-4444');
INSERT INTO TBL_MEMBER(SID,NAME,TEL) VALUES(MEMBERSEQ.NEXTVAL, '장현성', '010-5555-5555');

--확인

SELECT SID,NAME,TEL
FROM TBL_MEMBER
ORDER BY SID;

--한줄로
SELECT SID,NAME,TEL FROM TBL_MEMBER ORDER BY SID
;


COMMIT;


--인원수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBER;

--한줄

SELECT COUNT(*) AS COUNT FROM TBL_MEMBER
;

--SID로 회원데이터 검색

SELECT SID, NAME, TEL
FROM TBL_MEMBER
WHERE SID = 1;

--한줄

SELECT SID, NAME, TEL FROM TBL_MEMBER WHERE SID = 1
;

--회원 데이터 수정

UPDATE TBL_MEMBER
SET NAME='고연수', TEL='010-1110-0111'
WHERE SID=1;

--한줄

UPDATE TBL_MEMBER SET NAME='고연수', TEL='010-1110-0111' WHERE SID=1
;

ROLLBACK;

--○회원 데이터 삭제 쿼리문 구성
SELECT SID, NAME, TEL
FROM TBL_MEMBER
WHERE SID = 1;

--한줄

DELETE FROM TBL_MEMBER WHERE SID = 1
;

ROLLBACK;



--점수테이블 제거

DROP TABLE TBL_SCORE;


PURGE RECYCLEBIN;


CREATE TABLE TBL_MEMBERSCORE
( SID NUMBER
, KOR NUMBER(3)
, ENG NUMBER(3)
, MAT NUMBER(3)
, CONSTRAINT MEMBERSCORE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT MEMBERSCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_MAT_CK CHECK(MAT BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_SID_FK FOREIGN KEY(SID)
                                REFERENCES TBL_MEMBER(SID)
);

--Table TBL_MEMBERSCORE이(가) 생성되었습니다.

--샘플데이터 입력
INSERT INTO TBL_MEMBERSCORE(SID,KOR,ENG,MAT) VALUES(1, 90, 80, 70)
;


--○ 확인
SELECT SID, KOR, ENG, MAT FROM TBL_MEMBERSCORE
;

COMMIT;

--○성적 입력 인원 수 확인

SELECT COUNT(*) AS COUNT FROM TBL_MEMBERSCORE
;


--성적 데이터 검색
SELECT SID, KOR, ENG, MAT
FROM TBL_MEMBERSCORE
WHERE SID=1;


--한줄로
SELECT SID, KOR, ENG, MAT FROM TBL_MEMBERSCORE WHERE SID=1
;


--성적 데이터 수정

UPDATE TBL_MEMBERSCORE
SET KOR=99, ENG=99, MAT=90
WHERE SID=1;

--한줄

UPDATE TBL_MEMBERSCORE SET KOR=99, ENG=99, MAT=90 WHERE SID=1
;

--성적 데이터 삭제
SELECT *
FROM TBL_MEMBERSCORE
WHERE SID = 1;

DELETE FROM TBL_MEMBERSCORE WHERE SID = 1
;

--한줄로

DELETE FROM TBL_MEMBERSCORE WHERE SID = 1
;



ROLLBACK;

--○전체 데이터 조회 쿼리문 구성()
SELECT M.SID, M.NAME
      , NVL(MS.KOR,-1)
      , NVL(MS.ENG,-1)
      , NVL(MS.MAT,-1)
FROM TBL_MEMBER M JOIN TBL_MEMBERSCORE MS
ON M.SID = MS.SID(+);


--전체 데이터 조회전용 뷰(VIEW_MEMBERSCORE)생성

CREATE OR REPLACE VIEW VIEW_MEMBERSCORE
AS
SELECT M.SID , M.NAME
      , NVL(MS.KOR,-1) AS KOR
      , NVL(MS.ENG,-1) AS ENG
      , NVL(MS.MAT,-1) AS MAT
FROM TBL_MEMBER M JOIN TBL_MEMBERSCORE MS
ON M.SID = MS.SID(+);


--생성한 뷰(VIEW_MEMBERSCORE) 를 활용한 상세 리스트 조회 쿼리문 구성
-- 번호 이름 국어,영어,수학점수 총점 평균 석차


SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT,(KOR+ENG+MAT)/3 AS AVG
      , RANK() OVER(ORDER BY (KOR+ENG+MAT)  DESC) AS RANK
FROM VIEW_MEMBERSCORE;

/*
1	조현하	90	80	70	240	80	1
5	장현성	-1	-1	-1	-3	-1	2
4	반보영	-1	-1	-1	-3	-1	2
2	임시연	-1	-1	-1	-3	-1	2
3	최나윤	-1	-1	-1	-3	-1	2
*/

--○생성한 뷰 를 활용한 번호 검색
SELECT SID, NAME, KOR, ENG, MAT
FROM VIEW_MEMBERSCORE
WHERE SID=1;


--한줄구성
SELECT SID, NAME, KOR, ENG, MAT FROM VIEW_MEMBERSCORE WHERE SID=1
;


--참조 데이터 레코드 수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERSCORE
WHERE SID=2;
--성적 처리가 되었느냐 아니냐를 알수있다.
--다만 1:1관계라 좋은건 아님

--한줄

SELECT COUNT(*) AS COUNT FROM TBL_MEMBERSCORE WHERE SID=1
;
